### ISSUE TITLE
Debugging doesn't work?

### ISSUE THREAD

**Issue by Bartwillemsen** [JetBrains/Unity3dRider#40] opened 2016-12-02 11:09 UTC
Hello! I hope this is the right repository to raise this issue.

Since I updated Unity to 5.5, I am unable to debug my project through Rider. When I place a breakpoint somewhere and then click "Attach to local proccess" and select the Unity process, a red cross appears inside the breakpoint with the message "A breakpoint could not yet be bound to a valid location". Then when I try to run my game, it'll not break at the breakpoint and continue running.

![schermafdruk van 2016-12-02 12-04-13](https://cloud.githubusercontent.com/assets/1550822/20832012/1cc253a4-b888-11e6-8e7b-7e1f6b98f0a5.png)

As far as I am aware I am running the latest version of all integration plugins (This one and the Unity support plugin from the Rider plugin reposity) and Unity. 

Is there anything I am doing wrong?

**Comment by van800** [comment] 2016-12-02 11:10
true. we are investigation the issue https://youtrack.jetbrains.com/issue/RIDER-3588

**Comment by Bartwillemsen** [comment] 2016-12-02 11:12
Thanks! I'll keep an eye on that issue then. :)

**Comment by goibon** [comment] 2016-12-15 18:08
@van800 I see that the issue you have linked to is marked as "fixed in branch" (what great news :smiley:)
Do you have any estimate of when (EAP 15) will be released?
And do you know whether or not it works with the Unity3D 5.6 beta?

**Comment by van800** [comment] 2016-12-15 18:43
Eap15 must be published before 20th Dec, though it is not 100%, that this fix will be included. (

**Comment by goibon** [comment] 2016-12-27 19:40
@van800  It looks like it works in Eap15 in Unity3D 5.6b :+1:

**Comment by ASalihov** [comment] 2017-03-30 08:33
Same bug to me. March 22 2017 build

**Comment by patspam** [comment] 2017-05-26 06:55
I've started seeing this in the latest Rider build:

Rider 1.0 EAP
Build #RS-171.4456.199, built on May 18, 2017
Rider EAP User
Expiration date: June 17, 2017
JRE: 1.8.0_112-release-736-b17 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.4

**Comment by van800** [comment] 2017-05-26 07:22
@patspam What is your Unity3d version? What exactly are you seeing?
Before #RS-171.4456.199 was out I have tested the debugging with Unity 2017.1.0b5, so it is expected to function.

**Comment by patspam** [comment] 2017-05-26 07:27
Unity 5.5.3f1

Was previously working, pretty sure the only thing that's changed is my Rider version.

**Comment by van800** [comment] 2017-05-26 08:10
@patspam Have you tried it with Attach to process? What exactly are you seeing?
"A breakpoint could not yet be bound to a valid location"?
Please submit a request to https://youtrack.jetbrains.com/issues/RIDER and attach logs (zip everything from Help->Show log in Files)
Followup here with a link to request. Thanks!

**Comment by patspam** [comment] 2017-06-01 05:22
@van800 Yes, I am attempting to use Attach to process, and selecting the Unity process.

This was working until the most recent update. Confirmed on my second dev machine, and also with a colleague that this has stopped working for us.

To be precise, we are attempting to debug a .dll (as opposed to C# code in the Unity project itself).

YouTrack issue: https://youtrack.jetbrains.com/issue/RIDER-6762

**Closed** 2017-06-06 11:58 UTC
